<?php
namespace SlaxWeb\BaseModel;

/**
 * Constants for the Base Model
 *
 * @author Tomaz Lovrec <tomaz.lovrec@gmail.com>
 */
class Constants
{
    /**
     * Soft delete constants
     */
    const DELETEHARD = 100;
    const DELETESOFTMARK = 101;
    const DELETESOFTSTATUS = 102;

    /**
     * Primary key Constants
     */
    // Normal integer, not automatic incrementation of the key
    // Use of such is discouraged, if you do, you have to keep track of the key
    // value before inserting.
    const PKEYINT = 200;
    // Auto-Incrementet integer key
    const PKEYAI = 201;
    // Keys generated by a sql function UUID()
    const PKEYUUID = 202;
    // Keys generated by code functions
    const PKEYFUNC = 203;
}
