<?php
namespace SlaxWeb\BaseModel;

/**
 * Constants for the Base Model
 *
 * @author Tomaz Lovrec <tomaz.lovrec@gmail.com>
 */
class Constants
{
    /**
     * Soft delete constants
     */
    const DELETEHARD = 100;
    const DELETESOFTMARK = 101;
    const DELETESOFTSTATUS = 102;

    /**
     * Primary key Constants
     */
    // Auto-Incrementet integer key
    const PKEYAI = 200;
    // Keys generated by a sql function UUID()
    const PKEYUUID = 201;
    // Keys generated by code functions
    const PKEYFUNC = 202;
    // No primary key
    const PKEYNONE = 203;

    /**
     * Join constants
     */
    const JOININNER = "INNER";
    const JOINLEFT = "LEFT OUTTER";
    const JOINRIGHT = "RIGHT OUTTER";
}
